#include "giopi.h"

// getdigits.c
void getdigits(char *input, unsigned long *result);

// logging.c
void loginit(char *logfile, bool keeplog);
void logthis(char *filename, char *fmt, ...);
void logdone();

// split.c
void split(unsigned long b, unsigned long digits, unsigned long splits);

// root10005.c
void root10005(mpf_t r, unsigned long digits);

// divide.c
void divide(mpf_t r, mpf_t y, mpf_t x);

// output.c
void writetxt(mpf_t result, char *txtfile, unsigned long digits);
void writeraw(mpf_t result, char *rawfile, unsigned long digits);

// tmptxt.c
void tmptxt(unsigned long digits, bool showoutput, bool rawoutput, clock_t start_time, char *logfile, char *rawfile, char *txtfile);

void usage() {
  printf("Usage:     giopi [-d digits] [-1] [-2] [-4] [-8] [-n] [-r] [-h] [places]\n");
  printf("\n");
  printf("-d digits  Desired digits (prompted if digits not specified)\n");
  printf("places     Alternative to -d parameter (-d has priority if both used)\n");
  printf("-1/2/4/8   Use 1/2/4/8 way version of the binary split (default = 2)\n");
  printf("-n         Skip output file (useful for timing runs)\n");
  printf("-r         Generate raw output rather than text\n");
  printf("-h         Print this help text\n");
}

int main(int argc, char *argv[]) {
  unsigned long digits, places, count, terms, bits, splits;
  char          logfile[NAMESIZE], rawfile[NAMESIZE], txtfile[NAMESIZE];
  clock_t       start_time, inter_time;
  bool          showoutput, rawoutput;
  int           option;

  digits = 0;
  splits = 2;
  showoutput = true;
  rawoutput = false;

  while((option = getopt(argc, argv, "d:1248nrh")) != -1) {
    switch(option) {
      case 'd':
        getdigits(optarg, &places);
        if (places > 0) { digits = places; }
        break;
      case '1':
        splits = 1;
        break;
      case '2':
        splits = 2;
        break;
      case '4':
        splits = 4;
        break;
      case '8':
        splits = 8;
        break;
      case 'n':
        showoutput = false;
        break;
      case 'r':
        rawoutput = true;
        break;
      case 'h':
        usage();
        return EXIT_SUCCESS;
        break;
      default:
        usage();
        return EXIT_SUCCESS;
        break;
    }
  }

  if (digits == 0) {
    for ( ; optind < argc ; optind++) {
      getdigits(argv[optind], &places);
      if (places > 0) { digits = places; }
    }
  }

  if (digits == 0) {
    printf("Digits? ");
    scanf("%lu", &digits);
    if (digits == 0) {
      printf("ERROR: Invalid digit count\n");
      return EXIT_FAILURE;
    }
  }

  sprintf(logfile, "%lu.log", digits);
  sprintf(rawfile, "%lu.raw", digits);
  sprintf(txtfile, "%lu.txt", digits);
  loginit(logfile, false);

  terms = (digits / DIGITS_PER_ITER) + 1;
  bits = (digits * BITS_PER_DIGIT) + LEEWAY;
  mpf_set_default_prec(bits);

  logthis(logfile, "Build:  GioPi (%s)\n", BUILDDATE);
  logthis(logfile, "Digits: %lu\n", digits);
  logthis(logfile, "Terms:  %lu\n\n", terms);

  // binary split
  start_time = clock();
  logthis(NULL, "Split:\r");
  split(terms, digits, splits);
  logthis(logfile, "Split: (%lu) %9.2f seconds\n", splits, (double) (clock() - start_time) / CLOCKS_PER_SEC);

  // process pass-9-*.tmp files generated by split() for final result
  tmptxt(digits, showoutput, rawoutput, start_time, logfile, rawfile, txtfile);

  // tidy up
  logdone();

  return EXIT_SUCCESS;
}
