#include "giopi.h"

// getdigits.c
void getdigits(char *input, unsigned long *result);

// logging.c
void loginit(char *logfile, bool keeplog);
void logthis(char *filename, char *fmt, ...);
void logdone();

// split.c
void split(unsigned long b, unsigned long digits, unsigned long splits);

// root10005.c
void root10005(mpf_t r, unsigned long digits);

// divide.c
void divide(mpf_t r, mpf_t y, mpf_t x);

// output.c
void writetxt(mpf_t result, char *txtfile, unsigned long digits);
void writeraw(mpf_t result, char *rawfile, unsigned long digits);

// tmptxt.c
void tmptxt(unsigned long digits, bool showoutput, bool rawoutput, clock_t start_time, char *logfile, char *rawfile, char *txtfile);

// getopt_long structures
int           option_flag;
char          *short_option = "d:1248nrh?";
struct option long_options[] = {
  {"digits",  required_argument,  &option_flag,  0},
  {"DIGITS",  required_argument,  &option_flag,  0},
  {"splits",  required_argument,  &option_flag,  1},
  {"SPLITS",  required_argument,  &option_flag,  1},
  {"noout",   no_argument,        &option_flag,  2},
  {"NOOUT",   no_argument,        &option_flag,  2},
  {"rawout",  no_argument,        &option_flag,  3},
  {"RAWOUT",  no_argument,        &option_flag,  3},
  {"help",    no_argument,        &option_flag,  4},
  {"HELP",    no_argument,        &option_flag,  4},
  {0,         0,                  0,  0}
};

void usage() {
  printf("giopi [-d/--digits] digits [-1/-2/-4/-8] [--splits splits] [-n] [--noout] [-r] [--raw] [-h] [--help]\n");
  printf("\n");
  printf("-d digits / --digits digits / digits\n");
  printf("  Desired digits (prompted if digits not specified)\n");
  printf("  (digit-only used in preference to others, otherwise last value specified used)\n");
  printf("\n");
  printf("-1 / -2 / -4 / -8 / --splits splits\n");
  printf("  Use 1/2/4/8 way version of the binary split (default = 2, any other value ignored)\n");
  printf("\n");
  printf("-n / --noout\n");
  printf("  Skip output file (useful for timing runs)\n");
  printf("\n");
  printf("-r / --raw\n");
  printf("  Generate raw output rather than text\n");
  printf("\n");
  printf("-h / --help\n");
  printf("  Print this help text\n");
}

int main(int argc, char *argv[]) {
  unsigned long digits, value, count, terms, bits, splits;
  char          logfile[NAMESIZE], rawfile[NAMESIZE], txtfile[NAMESIZE];
  clock_t       start_time, inter_time;
  bool          showoutput, rawoutput;
  int           option, option_index;

  digits = 0;
  splits = 2;
  showoutput = true;
  rawoutput = false;

  while((option = getopt_long(argc, argv, short_option, long_options, &option_index)) != -1) {
    switch(option) {
      case 0:
        switch(option_flag) {
          case 0: // digits
            getdigits(optarg, &value);
            if (value > 0) { digits = value; }
            break;
          case 1: // splits
            getdigits(optarg, &value);
            if (value > 0) { splits = value; }
            break;
          case 2: // noout
            showoutput = false;
            break;
          case 3: // raw
            rawoutput = true;
            break;
          case 4: // help
            usage();
            return EXIT_SUCCESS;
            break;
        }
        break;
      case 'd':
        getdigits(optarg, &value);
        if (value > 0) { digits = value; }
        break;
      case '1':
        splits = 1;
        break;
      case '2':
        splits = 2;
        break;
      case '4':
        splits = 4;
        break;
      case '8':
        splits = 8;
        break;
      case 'n':
        showoutput = false;
        break;
      case 'r':
        rawoutput = true;
        break;
      case 'h':
      case '?':
        usage();
        return EXIT_SUCCESS;
        break;
      default:
        usage();
        return EXIT_SUCCESS;
        break;
    }
  }
  
  for ( ; optind < argc ; optind++) {
    getdigits(argv[optind], &value);
    if (value > 0) { digits = value; }
  }

  if (digits == 0) {
    printf("Digits? ");
    scanf("%lu", &digits);
    if (digits == 0) {
      printf("ERROR: Invalid digit count specified\n\n");
      usage();
      return EXIT_FAILURE;
    }
  }

  sprintf(logfile, "%lu.log", digits);
  sprintf(rawfile, "%lu.raw", digits);
  sprintf(txtfile, "%lu.txt", digits);
  loginit(logfile, false);

  terms = (digits / DIGITS_PER_ITER) + 1;
  bits = (digits * BITS_PER_DIGIT) + LEEWAY;
  mpf_set_default_prec(bits);

  logthis(logfile, "Build:  %s (%s - %s)\n", BUILDNAME, BUILDDATE, BUILDTYPE);
  logthis(logfile, "Digits: %lu\n", digits);
  logthis(logfile, "Terms:  %lu\n\n", terms);

  // binary split
  start_time = clock();
  logthis(NULL, "Split:\r");
  split(terms, digits, splits);
  logthis(logfile, "Split: (%lu) %9.2f seconds\n", splits, (double) (clock() - start_time) / CLOCKS_PER_SEC);

  // process pass-9-*.tmp files generated by split() for final result
  tmptxt(digits, showoutput, rawoutput, start_time, logfile, rawfile, txtfile);

  // tidy up
  logdone();

  return EXIT_SUCCESS;
}
